### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by raypurchasett** [akkadotnet/Akka.Persistence.Cassandra#16]
I've just noticed in our UAT environment we have trace log files that are GBs each. They're all full of logs from an actor that failed to write messages to cassandra. Stack trace looks like this:

> 21:10:10 - Error - Index was out of range. Must be non-negative and less than the size of the collection.
> Parameter name: index System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
> Parameter name: index
>    at System.Collections.Generic.List`1.get_Item(Int32 index)
>    at Akka.Persistence.Cassandra.Journal.CassandraJournal.WriteMessagesAsync(IEnumerable`1 messages)
>    at Akka.Persistence.Journal.AsyncWriteJournal.HandleWriteMessages(WriteMessages message)
>    at Akka.Persistence.Journal.AsyncWriteJournal.Receive(Object message)
>    at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
>    at Akka.Actor.ActorCell.ReceiveMessage(Object message)
>    at Akka.Actor.ActorCell.Invoke(Envelope envelope)    at System.Collections.Generic.List`1.get_Item(Int32 index)
>    at Akka.Persistence.Cassandra.Journal.CassandraJournal.WriteMessagesAsync(IEnumerable`1 messages)
>    at Akka.Persistence.Journal.AsyncWriteJournal.HandleWriteMessages(WriteMessages message)
>    at Akka.Persistence.Journal.AsyncWriteJournal.Receive(Object message)
>    at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
>    at Akka.Actor.ActorCell.ReceiveMessage(Object message)
>    at Akka.Actor.ActorCell.Invoke(Envelope 
> 
> envelope)

**Comment by raypurchasett** [comment]
Also just after this message (or before it's hard to tell) I'm getting an error 

'blah was killed after recovery failure (persistence id = blah). To avoid killing persistence actors on recovery failure it must handle RecoveryFailure messages etc.

This is happening many times a second for t he same actor though so clearly it's retrying the operation.

> 19:25:07 - Error - MyActor was killed after recovery failure (persistence id = MyActor-17047-2). To avoid killing persistent actors on recovery failure, a PersistentActor must handle RecoveryFailure messages. Recovery failure was caused by: One or more errors occurred. Akka.Actor.ActorKilledException: MyActor was killed after recovery failure (persistence id = MyActor -17047-2). To avoid killing persistent actors on recovery failure, a PersistentActor must handle RecoveryFailure messages. Recovery failure was caused by: One or more errors occurred.
>    at Akka.Persistence.Eventsourced.Unhandled(Object message)
>    at Akka.Persistence.UntypedPersistentActor.ReceiveRecover(Object message)
>    at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
>    at Akka.Persistence.Eventsourced.<>c__DisplayClass17.<ReplayStarted>b__16(Receive receive, Object message)
>    at Akka.Persistence.Eventsourced.AroundReceive(Receive receive, Object message)
>    at Akka.Actor.ActorCell.ReceiveMessage(Object message)
>    at Akka.Actor.ActorCell.Invoke(Envelope envelope)    at Akka.Persistence.Eventsourced.Unhandled(Object message)
>    at Akka.Persistence.UntypedPersistentActor.ReceiveRecover(Object message)
>    at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
>    at Akka.Persistence.Eventsourced.<>c__DisplayClass17.<ReplayStarted>b__16(Receive receive, Object message)
>    at Akka.Persistence.Eventsourced.AroundReceive(Receive receive, Object message)
>    at Akka.Actor.ActorCell.ReceiveMessage(Object message)
>    at Akka.Actor.ActorCell.Invoke(Envelope envelope)

**Comment by Horusiath** [comment]
It looks that the most probable reason of an error lies [here](https://github.com/akkadotnet/Akka.Persistence.Cassandra/blob/dev/src/Akka.Persistence.Cassandra/Journal/CassandraJournal.cs#L189). From the [JVM source](https://github.com/krasserm/akka-persistence-cassandra/blob/master/src/main/scala/akka/persistence/cassandra/journal/CassandraJournal.scala#L114) it looks like the 0-length event collection are allowed in this context.

**Comment by raypurchasett** [comment]
Not sure how it even gets to the place of trying to write 0 events

**Comment by raypurchasett** [comment]
Closing. Fixed in #16
