### ISSUE TITLE
Feature idea - add configurable TTL option for journaled messages and snapshots

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/Akka.Persistence.Cassandra#9]
Thinking we could enable a setting via HOCON for journaled messages and snapshots to set a TTL duration for messages / snapshots. It'd be disabled by default but could be turned on via

```
akka.persistence.cassandra{
     journal.ttl = 4 d
     snapshot.ttl = 10 d
}
```

**Comment by rogeralsing** [comment]
The whole point of Akka.Persistence is to keep a full record of past events, deleting old events would bring you back to an incomplete state.

I do get that this could be useful for e.g. a chat where you want to discard messages older than x time, and when the chatroom reboots, it only holds the x days latest events.
_but_ is that really the responsibility of Akka.Persistence or its providers?

I'm thinking project scope creep. even if I see when it can be used.

**Comment by Horusiath** [comment]
There is a special message type `DeleteMessagesTo(pid, seqNr, isPermanent)`, which when send to journal, will cause it to drop events for a particular persistent actor event stream, up to event with seqence nr provided in message.

In general events should never be dropped, as this could cause persistent actor to recover in corrupted state. The only justified case I see, is that your events from far past are no longer necessary and occupy to much memory. In that caseyou may decide to snapshots actor's state and drop the events that happened before it.

**Comment by Aaronontheweb** [comment]
Ok, got it - great points. This is something that should be taken care of inside the actor's code rather than using a database feature to do it.
